/*

this fie can be used to initialise the data
use the variable ~leuchtstoffraum_datapath to point to where your data folder.

~leuchtstoffraum_datapath = "path/to/folder"

It should look like this:

// peaks files:

path/to/folder/peaks/

// spectrum files

path/to/folder/fits/

// ordered spectral data

path/to/folder/fits_ordered

*/

// run this line for init:

loadRelative("Library/init-all.scd");

